# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Schemagic Total SEO Schema"
client_id = "51d478c5cd6e53e9c22d3666397cefd4"
application_url = "https://hk-fin-radios-prospective.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags,read_script_tags"

[auth]
redirect_urls = [
  "https://hk-fin-radios-prospective.trycloudflare.com/auth/callback",
  "https://hk-fin-radios-prospective.trycloudflare.com/auth/shopify/callback",
  "https://hk-fin-radios-prospective.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "havanor-test-store.myshopify.com"
